spring:
  main:
    banner-mode: off
  cache:
    cache-names: "targets"
    caffeine:
      spec: "maximumSize=256,expireAfterWrite=10m"

server:
  port : 9218

management:
  endpoints:
    web.base-path: /
    web:
      exposure:
        include: health, prometheus
      path-mapping:
        prometheus: metrics
