version: '2.4'
services:

  prometheus:
    image: prom/prometheus:v2.48.0
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    ports:
    - 9090:9090

  tls-grade-exporter:
    image: ping7io/tls-grade-exporter:latest
    ports:
      - 9218:9218
