name: continuous integration

on:
  push:
    branches:
      - master
      - main
      - feature/**
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
        cache: 'maven'

    - name: build JAR from Maven
      run: mvn --batch-mode --no-transfer-progress  clean verify

    - name: build Docker file
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
