name: release
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

    - name: Log in to GitHub Docker Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
        cache: 'maven'

    - name: build JAR from Maven
      run: mvn --batch-mode --no-transfer-progress  clean verify -DskipTests=true

    - name: build Docker file
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: |
          ghcr.io/ping7io/tls-grade-exporter:latest
